<script setup>
import { ref, onMounted, onUnmounted, onBeforeMount } from "vue";
import CatalogItem from "../components/CatalogItem.vue";
// import { GoogleSpreadsheet } from "google-spreadsheet";
// import credentials from "../../rentcarns.json";
import VueDatePicker from "@vuepic/vue-datepicker";
// import { JWT } from 'google-auth-library';

// const serviceAccountAuth = new JWT({
//   // env var values here are copied from service account credentials generated by google
//   // see "Authentication" section in docs for more info
//   email: import.meta.env.VITE_GOOGLE_CLIENT_EMAIL,
//   key: import.meta.env.VITE_GOOGLE_PRIVATE_KEY,
//   scopes: [
//     'https://www.googleapis.com/auth/spreadsheets',
//   ],
// });

const date = ref();
const tg = window.Telegram.WebApp;
const name = ref("");
const selectedCar = ref("");

const data = ref({});
const queryId = ref(null);

// const accessSpreadSheet = async () => {
//   const key = import.meta.env.VITE_GOOGLE_PRIVATE_KEY.replace(/\\n/g, "\n");
//   const doc = new GoogleSpreadsheet(import.meta.env.VITE_GOOGLE_SHEET_ID);
//   await doc.useServiceAccountAuth({
//     client_email: import.meta.env.VITE_GOOGLE_CLIENT_EMAIL,
//     private_key: key,
//   });
//   await doc.loadInfo();
//   console.log(doc);

//   const sheet = doc.sheetsByIndex[0];
//   const rows = await sheet.getRows({
//     offset: 1,
//   });
//   console.log(rows);
//   console.log(doc.title);
// };

const onSendData = async () => {
  // const content = await response.json();
  // console.log(content);
  // inputName.value = '';
  // tg.sendData(JSON.stringify(data.value));
  tg.showAlert("done!");
};

onBeforeMount(() => {
  // accessSpreadSheet();
});

onMounted(() => {
  name.value = tg.initDataUnsafe?.user?.username;
  queryId.value = tg.initDataUnsafe?.query_id;
  tg.ready();
  tg.MainButton.onClick(onSendData);
});
onUnmounted(() => {
  tg.MainButton.offClick(onSendData);
});
const onClose = () => {
  tg.close();
};
const showMainButton = () => {
  if (tg.MainButton.isVisible) {
    tg.MainButton.hide();
  } else {
    tg.MainButton.show();
  }
};
const catalog = [
  {
    id: 1,
    name: "Audi A3 Cabrio",
    price: 45,
    count: 0,
    img: "/src/assets/audi.webp",
  },
  {
    id: 2,
    name: "Mini Cooper Cabrio",
    price: 50,
    count: 0,
    img: "/src/assets/mini.webp",
  },
  {
    id: 3,
    name: "Renault Laguna",
    price: 20,
    count: 0,
    img: "/src/assets/renault.webp",
  },
];
const onAddBtnClick = (payload) => {
  console.log(payload);
  selectedCar.value = payload;
};
</script>

<template>
  <div class="flex flex-col gap-6 items-center">
    <button type="button" @click="onSendData">send data test</button>
    <h1>hello!</h1>
    <button type="button" @click="showMainButton">ShowMainBtn</button>
    <div class="catalog flex flex-wrap gap-5">
      <CatalogItem
        v-for="item in catalog"
        :key="item.id"
        :item="item"
        @onAddBtnClick="onAddBtnClick"
      ></CatalogItem>
    </div>
    <div v-show="selectedCar">
      <VueDatePicker
        v-model="date"
        range
        placeholder="Choose date"
        :enable-time-picker="false"
        uid="bookdate"
      />
    </div>
    <button v-show="date" class="px-3 py-2 border" type="button">
      Send request
    </button>
  </div>
</template>

<style scoped></style>
